name: Auto-merge bot updates

on:
  push:
    branches: [ bot/updates ]
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  merge-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "aifs-bot"
          git config user.email "bot@aifinancialservicesinc.com"
      - name: Ensure main exists
        run: |
          if ! git show-ref --verify --quiet refs/heads/main; then
            echo "main branch not found; creating from default HEAD"
            git branch -M main
          fi
      - name: Merge bot/updates -> main
        run: |
          git checkout main
          git merge --no-edit --strategy-option theirs bot/updates || true
          git push origin main
